version: 2.1

orbs:
  # Using 1.0 of our Orbs means it will use the latest 1.0.x version from https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@1.0

# YAML anchors for some common/repeated values
x-common-params:
  - &xcode-version "11.2.1"
  - &workspace "WordPressUI.xcworkspace"
  - &ios-version "13.2.2"
  - &podspec "WordPressUI.podspec"
  - &on-tags-only
      tags:
        only: /.*/
      branches:
        ignore: /.*/

workflows:
  test_and_validate:
    jobs:
      - ios/test:
          name: Unit Tests
          xcode-version: *xcode-version
          workspace: *workspace
          scheme: WordPressUI
          device: iPhone 11
          ios-version: *ios-version
          bundle-install: false
          pod-install: false
      - ios/test:
          name: UI Tests
          xcode-version: *xcode-version
          workspace: *workspace
          scheme: Example
          device: iPhone 11
          ios-version: *ios-version
          bundle-install: false
          pod-install: false
      - ios/validate-podspec:
          name: Validate Podspec
          xcode-version: *xcode-version
          podspec-path: *podspec
          bundle-install: true
