version: 2.1

orbs:
  # Using 1.0 of our Orbs means it will use the latest 1.0.x version from https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@1.0

workflows:
  test_and_validate:
    jobs:
      - ios/test:
          name: Unit Tests
          xcode-version: "11.2.1"
          workspace: WordPressUI.xcworkspace
          scheme: WordPressUI
          device: iPhone 11
          ios-version: "13.2.2"
          bundle-install: false
          pod-install: false
      - ios/test:
          name: UI Tests
          xcode-version: "11.2.1"
          workspace: WordPressUI.xcworkspace
          scheme: Example
          device: iPhone 11
          ios-version: "13.2.2"
          bundle-install: false
          pod-install: false
      - ios/validate-podspec:
          name: Validate Podspec
          xcode-version: "11.2.1"
          podspec-path: WordPressUI.podspec
          bundle-install: true
      - ios/publish-podspec:
          name: Publish to Trunk
          xcode-version: "10.2.0"
          podspec-path: WordPressUI.podspec
          bundle-install: true
          post-to-slack: true
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
