# frozen_string_literal: true

default_platform(:ios)

SWIFTLINT_PLUGIN_VALIDATION_BYPASS_XCARGS = '-skipPackagePluginValidation -skipMacroValidation'

platform :ios do
  desc 'Builds the project and runs tests'
  lane :test do
    run_tests(
      package_path: '.',
      scheme: 'WordPressUI',
      device: 'iPhone 14',
      prelaunch_simulator: true,
      buildlog_path: File.join(__dir__, '.build', 'logs'),
      derived_data_path: File.join(__dir__, '.build', 'derived-data'),
      xcargs: SWIFTLINT_PLUGIN_VALIDATION_BYPASS_XCARGS
    )
  end
end
